// Reproducible build of the hardware-probe WASM kernel: compiles assembly/matmul.ts with
// AssemblyScript and writes the bytes, base64-embedded, into src/engine/mm.generated.ts.
// Run via `npm run build:wasm` whenever assembly/matmul.ts changes; the generated file is committed
// so the normal `tsup` build (and CI publish) needs no compiler. Deterministic for a pinned asc.
//
// Usage:
//   node scripts/build-wasm.mjs           # (re)generate src/engine/mm.generated.ts
//   node scripts/build-wasm.mjs --check   # exit non-zero if the committed file is stale (CI guard)

import asc from 'assemblyscript/asc'
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const OUT = resolve(root, 'src/engine/mm.generated.ts')
const checkOnly = process.argv.includes('--check')

let wasm = null
const { error, stderr } = await asc.main(
  [
    'assembly/matmul.ts',
    '--outFile', 'matmul.wasm',
    '--optimize',
    '--optimizeLevel', '3',
    '--shrinkLevel', '0',
    '--runtime', 'stub',
    '--noAssert',
  ],
  {
    baseDir: root,
    writeFile(name, contents) {
      if (name.endsWith('.wasm')) wasm = Buffer.from(contents)
    },
  },
)
if (error) {
  console.error('[build-wasm] AssemblyScript failed:\n' + stderr.toString())
  process.exit(1)
}
if (!wasm) {
  console.error('[build-wasm] no .wasm was emitted')
  process.exit(1)
}

const b64 = wasm.toString('base64')
const chunks = b64.match(/.{1,100}/g).map((s) => `  '${s}'`).join(' +\n')
const generated =
  `// GENERATED by scripts/build-wasm.mjs from assembly/matmul.ts - DO NOT EDIT BY HAND.\n` +
  `// Regenerate: npm run build:wasm\n` +
  `export const MM_WASM_B64 =\n${chunks}\n`

if (checkOnly) {
  let current = ''
  try {
    current = readFileSync(OUT, 'utf8')
  } catch {
    /* missing -> stale */
  }
  if (current !== generated) {
    console.error(
      '[build-wasm] src/engine/mm.generated.ts is stale or missing; run `npm run build:wasm` and commit.',
    )
    process.exit(1)
  }
  console.log('[build-wasm] generated file is up to date')
  process.exit(0)
}

writeFileSync(OUT, generated)
console.log(`[build-wasm] wrote ${OUT}  (wasm ${wasm.length} B, base64 ${b64.length} chars)`)
